version: '3.8'
services:
  server:
    build: ./server
    container_name: bs_server_container
    ports:
      - '8090:8090'
    env_file:
      - .env
  client:
    build: ./client
    container_name: bs_cleint_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    links: 
      - server